/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LihatDataPage extends javax.swing.JFrame {

    DataTodo dataTodo;
    DefaultTableModel modeltodo;
    /**
     * Creates new form HomePageUser
     */
    public LihatDataPage() {
        initComponents();
        setVisible(true);
        dataTodo = new DataTodo();
//        viewDataTabel();
        showDBtoTB();
    }
    public final void viewDataTabel(){
        String[] namakolom = {"Judul","Tenggat Waktu"};
        Object[] objecttodo = new Object[dataTodo.getAll().size()];
        modeltodo = new DefaultTableModel();
        modeltodo.addColumn("Judul");
        modeltodo.addColumn("Tenggat Waktu");
        tbData.setModel(modeltodo);
        
        int i=0;
        for(Todo todo: dataTodo.getAll()){
          modeltodo.addRow(
          new Object[]{
          todo.getTittle(),
          todo.getTenggatwaktu()
          }
          );
//            Object arraytodo[] = {
//                todo.getTittle(),
//                todo.getTenggatwaktu()
//            };
//            
//            objecttodo[i] = arraytodo;
//            modeltodo.addRow(objecttodo);
//            i++;
        }
    }
    private void showDBtoTB(){
        //mengkoneksikan ke database tabel mobil
        ResultSet resultSet = null;
        try {
            Connection connection = new koneksiDatabase().getKoneksi();
            Statement statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM todo_item");
        } catch (SQLException ex) {
            
        }
        
        //membuat judul kolom tabel
        modeltodo =new DefaultTableModel();
        modeltodo.addColumn("Judul");
        modeltodo.addColumn("Tenggat Waktu");
        tbData.setModel(modeltodo);
        
        //mengambil data dari database
        try {
            while(resultSet.next()){
            modeltodo.addRow(new Object[]{
                resultSet.getString("tittle"),
                resultSet.getString("tenggat_waktu"),
                });
            }
        } catch(SQLException ex) {
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btToTambahData = new javax.swing.JButton();
        btToSortirData = new javax.swing.JButton();
        btToUbahData = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        btToHapusData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btToTambahData.setText("Tambah Data");
        btToTambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToTambahDataActionPerformed(evt);
            }
        });

        btToSortirData.setText("Sortir Data");
        btToSortirData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToSortirDataActionPerformed(evt);
            }
        });

        btToUbahData.setText("Ubah Data");
        btToUbahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToUbahDataActionPerformed(evt);
            }
        });

        btLogout.setText("Logout");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btToHapusData.setText("Hapus Data");
        btToHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btToHapusDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btToTambahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btToSortirData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btToHapusData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btToUbahData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btToTambahData)
                .addGap(27, 27, 27)
                .addComponent(btToSortirData)
                .addGap(31, 31, 31)
                .addComponent(btToHapusData)
                .addGap(29, 29, 29)
                .addComponent(btToUbahData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btLogout)
                .addGap(69, 69, 69))
        );

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Judul", "Tenggat Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btToTambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToTambahDataActionPerformed
        // TODO add your handling code here:
        new TambahDataPage();
        dispose();
    }//GEN-LAST:event_btToTambahDataActionPerformed

    private void btToSortirDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToSortirDataActionPerformed
//        // TODO add your handling code here:
//        dispose();
          sortirRecord();
    }//GEN-LAST:event_btToSortirDataActionPerformed

    private void btToHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToHapusDataActionPerformed
      hapusRecord();
      showDBtoTB();
    }//GEN-LAST:event_btToHapusDataActionPerformed

    private void btToUbahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btToUbahDataActionPerformed
        // TODO add your handling code here:
        new UbahDataPage();
        dispose();
    }//GEN-LAST:event_btToUbahDataActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
        new LoginUser();
        dispose();
    }//GEN-LAST:event_btLogoutActionPerformed
    private void hapusRecord(){
        int column = 0;
        int row = tbData.getSelectedRow();
        String judul = tbData.getModel().getValueAt(row, column).toString();
        System.out.println(judul);
        String sql = """
                DELETE FROM todo_item WHERE tittle=?
                """;
        try (
                java.sql.Connection connection = new koneksiDatabase().getKoneksi();
                java.sql.PreparedStatement statement = connection.prepareStatement(sql)
        ) {
            statement.setString(1, judul);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
     }}
    
    private void sortirRecord(){
        List<Todo> todolist =  new ArrayList<>();
        ResultSet resultSet = null;
        try {
            Connection connection = new koneksiDatabase().getKoneksi();
            Statement statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM todo_item");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        try {
            while (resultSet.next()){
                Todo todo = new Todo();
                todo.setTittle(resultSet.getString("tittle"));
                todo.setTenggatwaktu(new java.util.Date(resultSet.getDate("tenggat_waktu").getTime()));
                todolist.add(todo);
            }
        } catch (Exception e) {
        }
        Collections.sort(todolist, new sortingTodo());
        
         //membuat judul kolom tabel
        modeltodo =new DefaultTableModel();
        modeltodo.addColumn("Judul");
        modeltodo.addColumn("Tenggat Waktu");
        tbData.setModel(modeltodo);
        
        for (Todo todo:todolist){
            modeltodo.addRow(new Object[]{
                todo.getTittle(),
                todo.getTenggatwaktu()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatDataPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatDataPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btToHapusData;
    private javax.swing.JButton btToSortirData;
    private javax.swing.JButton btToTambahData;
    private javax.swing.JButton btToUbahData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbData;
    // End of variables declaration//GEN-END:variables

    private void getData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
